export const blogsData = [
  {
    id: 1,
    title: "Shopify SEO: 5 Tipps zur Verbesserung deines Rankings",
    description: "Mit diesen SEO-Strategien holst du mehr Traffic auf deinen Shopify-Shop.",
    image: "/images/projects/menglu_paris.webp",
    tag: ["Alle", "Shopify"],
    gitUrl: "/",
    pageUrl: "/blog/shopify-seo",  
  },
  {
    id: 2,
    slug: "varalida", // <--- neu
    title: "Varalida - Creation of the entire store",
    description: "Project 2 description",
    image: "/images/projects/varalida.webp",
    tag: ["Alle", "Shopify"],
    gitUrl: "/",
    pageUrl: "/projects/varalida",  
  },
  {
    id: 3,
    slug: "death-night",
    title: "Death Night - Speed Optimization & Troubleshooting",
    description: "Project 3 description",
    image: "/images/projects/death_night.webp",
    tag: ["Alle", "Shopify"],
    gitUrl: "/",
    pageUrl: "/projects/death-night",  
  },
  {
    id: 4,
    slug: "baumawelt",
    title: "Baumawelt - Creation of the entire store",
    description: "Project 4 description",
    image: "/images/projects/baumawelt.webp",
    tag: ["Alle", "Shopify"],
    gitUrl: "/",
    pageUrl: "/projects/baumawelt",  
  },
  {
    id: 5,
    slug: "react-firebase-template",
    title: "React Firebase Template",
    description: "Authentication and CRUD operations",
    image: "/images/projects/5.png",
    tag: ["Alle", "Web"],
    gitUrl: "/",
    pageUrl: "/projects/react-firebase-template",  
  },
  {
    id: 6,
    slug: "fullstack-roadmap",
    title: "Full-stack Roadmap",
    description: "Project 5 description",
    image: "/images/projects/6.png",
    tag: ["Alle", "Web"],
    gitUrl: "/",
    pageUrl: "/projects/fullstack-roadmap",  
  },
]; 